services:
  frontend:
    build:
      context: .
    ports:
      - "12000:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    networks:
      - default
    environment:
      - HOGE=1
volumes:
  node_modules:
