services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "12000:3000"
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    networks:
      - default
    environment:
      - HOGE=1
  backend:
    build:
      context: ./backend
    ports:
      - "3001:80"
    volumes:
      - ./backend:/app
    networks:
      - default
    environment:
      - FUGA=1
volumes:
  node_modules:
